# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "994ff882388c77503c8dd75ea50ba4fa"
name = "Countdown Timer"
handle = "countdown-timer-104"
application_url = "https://operating-t-alloy-delay.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-e3dcdedc.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://operating-t-alloy-delay.trycloudflare.com/auth/callback",
  "https://operating-t-alloy-delay.trycloudflare.com/auth/shopify/callback",
  "https://operating-t-alloy-delay.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2025-07"

[pos]
embedded = false
